/********************************************************************************
** Form generated from reading UI file 'settingswidgetcommon.ui'
**
** Created by: Qt User Interface Compiler version 5.4.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SETTINGSWIDGETCOMMON_H
#define UI_SETTINGSWIDGETCOMMON_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_SettingsWidgetCommon
{
public:
    QFrame *frame_axis;
    QLabel *label_axis;
    QComboBox *comboBox_axis;
    QLabel *label_colorX;
    QPushButton *pushButton_colorX;
    QLabel *label_colorY;
    QPushButton *pushButton_colorY;
    QLabel *label_colorZ;
    QPushButton *pushButton_colorZ;
    QFrame *line_axisBottom;
    QFrame *line_axisTop;
    QFrame *line_axisLeft;
    QFrame *line;
    QFrame *frame;
    QFrame *line_axisLeft_2;
    QFrame *line_2;
    QFrame *line_axisBottom_2;
    QFrame *line_axisTop_2;
    QLabel *label;
    QCheckBox *checkBox_netEnabled;
    QDoubleSpinBox *spinBox_netWidth;
    QLabel *label_2;
    QPushButton *pushButton_netColor;
    QLabel *label_netColor;
    QFrame *frame_2;
    QFrame *line_axisLeft_3;
    QFrame *line_3;
    QFrame *line_axisBottom_3;
    QFrame *line_axisTop_3;
    QLabel *label_4;
    QCheckBox *checkBox_isonetEnabled;
    QDoubleSpinBox *spinBox_isonetWidth;
    QLabel *label_5;
    QPushButton *pushButton_isonetColor;
    QLabel *label_isonetColor;
    QComboBox *comboBox_isolinePeriodicy;
    QFrame *frame_axis_2;
    QLabel *label_axis_2;
    QFrame *line_axisBottom_4;
    QFrame *line_axisTop_4;
    QFrame *line_axisLeft_4;
    QFrame *line_4;
    QCheckBox *checkBox_timeEnabled;
    QLabel *label_9;
    QLineEdit *lineEdit_timeVariableName;
    QLabel *label_3;
    QDoubleSpinBox *spinBox_timeStep;
    QFrame *frame_3;
    QFrame *line_axisLeft_5;
    QFrame *line_5;
    QFrame *line_axisBottom_5;
    QFrame *line_axisTop_5;
    QLabel *label_10;
    QLabel *label_12;
    QLabel *label_15;
    QDoubleSpinBox *spinBox_radius;
    QLabel *label_16;
    QDoubleSpinBox *spinBox_scaleRate;
    QComboBox *comboBox_surfaceQuality;
    QFrame *frame_4;
    QFrame *line_axisLeft_6;
    QFrame *line_6;
    QFrame *line_axisBottom_6;
    QFrame *line_axisTop_6;
    QLabel *label_13;
    QLineEdit *lineEdit_configFile;
    QLabel *label_14;
    QPushButton *pushButton_configFile;
    QComboBox *comboBox_movingButton;
    QLabel *label_17;
    QLabel *label_6;
    QCheckBox *checkBox_isLegendShowed;
    QSlider *slider_legendSize;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QFrame *line_7;
    QFrame *line_9;
    QLabel *label_21;
    QLabel *label_22;
    QSlider *slider_verticalscale;
    QSlider *slider_legendOpacity;
    QLabel *label_23;
    QLabel *label_24;
    QFrame *line_10;
    QCheckBox *checkBox_perspective;
    QCheckBox *checkBox_proportions;
    QLineEdit *lineEdit_functionString;
    QLabel *label_function;

    void setupUi(QWidget *SettingsWidgetCommon)
    {
        if (SettingsWidgetCommon->objectName().isEmpty())
            SettingsWidgetCommon->setObjectName(QStringLiteral("SettingsWidgetCommon"));
        SettingsWidgetCommon->resize(1341, 249);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(SettingsWidgetCommon->sizePolicy().hasHeightForWidth());
        SettingsWidgetCommon->setSizePolicy(sizePolicy);
        frame_axis = new QFrame(SettingsWidgetCommon);
        frame_axis->setObjectName(QStringLiteral("frame_axis"));
        frame_axis->setGeometry(QRect(1190, 60, 141, 181));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        frame_axis->setPalette(palette);
        frame_axis->setAutoFillBackground(true);
        frame_axis->setFrameShape(QFrame::StyledPanel);
        frame_axis->setFrameShadow(QFrame::Raised);
        label_axis = new QLabel(frame_axis);
        label_axis->setObjectName(QStringLiteral("label_axis"));
        label_axis->setGeometry(QRect(20, 20, 101, 21));
        QFont font;
        font.setPointSize(14);
        label_axis->setFont(font);
        label_axis->setAlignment(Qt::AlignCenter);
        comboBox_axis = new QComboBox(frame_axis);
        comboBox_axis->setObjectName(QStringLiteral("comboBox_axis"));
        comboBox_axis->setGeometry(QRect(20, 50, 101, 22));
        QFont font1;
        font1.setPointSize(10);
        comboBox_axis->setFont(font1);
        label_colorX = new QLabel(frame_axis);
        label_colorX->setObjectName(QStringLiteral("label_colorX"));
        label_colorX->setGeometry(QRect(100, 80, 21, 21));
        QPalette palette1;
        QBrush brush1(QColor(255, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_colorX->setPalette(palette1);
        label_colorX->setAutoFillBackground(true);
        pushButton_colorX = new QPushButton(frame_axis);
        pushButton_colorX->setObjectName(QStringLiteral("pushButton_colorX"));
        pushButton_colorX->setGeometry(QRect(20, 80, 71, 23));
        pushButton_colorX->setFont(font1);
        label_colorY = new QLabel(frame_axis);
        label_colorY->setObjectName(QStringLiteral("label_colorY"));
        label_colorY->setGeometry(QRect(100, 110, 21, 21));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Base, brush1);
        QBrush brush2(QColor(0, 255, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        label_colorY->setPalette(palette2);
        label_colorY->setAutoFillBackground(true);
        pushButton_colorY = new QPushButton(frame_axis);
        pushButton_colorY->setObjectName(QStringLiteral("pushButton_colorY"));
        pushButton_colorY->setGeometry(QRect(20, 110, 71, 23));
        pushButton_colorY->setFont(font1);
        label_colorZ = new QLabel(frame_axis);
        label_colorZ->setObjectName(QStringLiteral("label_colorZ"));
        label_colorZ->setGeometry(QRect(100, 140, 21, 21));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        QBrush brush3(QColor(0, 0, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        label_colorZ->setPalette(palette3);
        label_colorZ->setAutoFillBackground(true);
        pushButton_colorZ = new QPushButton(frame_axis);
        pushButton_colorZ->setObjectName(QStringLiteral("pushButton_colorZ"));
        pushButton_colorZ->setGeometry(QRect(20, 140, 71, 23));
        pushButton_colorZ->setFont(font1);
        line_axisBottom = new QFrame(frame_axis);
        line_axisBottom->setObjectName(QStringLiteral("line_axisBottom"));
        line_axisBottom->setGeometry(QRect(10, 160, 119, 20));
        line_axisBottom->setFrameShape(QFrame::HLine);
        line_axisBottom->setFrameShadow(QFrame::Sunken);
        line_axisTop = new QFrame(frame_axis);
        line_axisTop->setObjectName(QStringLiteral("line_axisTop"));
        line_axisTop->setGeometry(QRect(10, 0, 119, 20));
        line_axisTop->setFrameShape(QFrame::HLine);
        line_axisTop->setFrameShadow(QFrame::Sunken);
        line_axisLeft = new QFrame(frame_axis);
        line_axisLeft->setObjectName(QStringLiteral("line_axisLeft"));
        line_axisLeft->setGeometry(QRect(0, 9, 20, 161));
        line_axisLeft->setFrameShape(QFrame::VLine);
        line_axisLeft->setFrameShadow(QFrame::Sunken);
        line = new QFrame(frame_axis);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(120, 10, 20, 160));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        frame = new QFrame(SettingsWidgetCommon);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(10, 90, 141, 151));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush);
        frame->setPalette(palette4);
        frame->setAutoFillBackground(true);
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        line_axisLeft_2 = new QFrame(frame);
        line_axisLeft_2->setObjectName(QStringLiteral("line_axisLeft_2"));
        line_axisLeft_2->setGeometry(QRect(0, 9, 20, 131));
        line_axisLeft_2->setFrameShape(QFrame::VLine);
        line_axisLeft_2->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(frame);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(120, 10, 20, 131));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_axisBottom_2 = new QFrame(frame);
        line_axisBottom_2->setObjectName(QStringLiteral("line_axisBottom_2"));
        line_axisBottom_2->setGeometry(QRect(10, 130, 119, 20));
        line_axisBottom_2->setFrameShape(QFrame::HLine);
        line_axisBottom_2->setFrameShadow(QFrame::Sunken);
        line_axisTop_2 = new QFrame(frame);
        line_axisTop_2->setObjectName(QStringLiteral("line_axisTop_2"));
        line_axisTop_2->setGeometry(QRect(10, 0, 119, 20));
        line_axisTop_2->setFrameShape(QFrame::HLine);
        line_axisTop_2->setFrameShadow(QFrame::Sunken);
        label = new QLabel(frame);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 20, 101, 21));
        label->setFont(font);
        label->setAlignment(Qt::AlignCenter);
        checkBox_netEnabled = new QCheckBox(frame);
        checkBox_netEnabled->setObjectName(QStringLiteral("checkBox_netEnabled"));
        checkBox_netEnabled->setEnabled(true);
        checkBox_netEnabled->setGeometry(QRect(20, 50, 101, 21));
        checkBox_netEnabled->setFont(font1);
        checkBox_netEnabled->setIconSize(QSize(16, 16));
        checkBox_netEnabled->setChecked(true);
        spinBox_netWidth = new QDoubleSpinBox(frame);
        spinBox_netWidth->setObjectName(QStringLiteral("spinBox_netWidth"));
        spinBox_netWidth->setGeometry(QRect(71, 80, 51, 22));
        spinBox_netWidth->setFont(font1);
        spinBox_netWidth->setDecimals(1);
        spinBox_netWidth->setMinimum(0.5);
        spinBox_netWidth->setMaximum(5);
        spinBox_netWidth->setSingleStep(0.1);
        spinBox_netWidth->setValue(1);
        label_2 = new QLabel(frame);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 80, 41, 21));
        label_2->setFont(font1);
        pushButton_netColor = new QPushButton(frame);
        pushButton_netColor->setObjectName(QStringLiteral("pushButton_netColor"));
        pushButton_netColor->setGeometry(QRect(20, 110, 71, 21));
        pushButton_netColor->setFont(font1);
        label_netColor = new QLabel(frame);
        label_netColor->setObjectName(QStringLiteral("label_netColor"));
        label_netColor->setGeometry(QRect(100, 110, 21, 21));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush4(QColor(0, 0, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush4);
        label_netColor->setPalette(palette5);
        label_netColor->setAutoFillBackground(true);
        frame_2 = new QFrame(SettingsWidgetCommon);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(1020, 60, 161, 181));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush);
        frame_2->setPalette(palette6);
        frame_2->setAutoFillBackground(true);
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        line_axisLeft_3 = new QFrame(frame_2);
        line_axisLeft_3->setObjectName(QStringLiteral("line_axisLeft_3"));
        line_axisLeft_3->setGeometry(QRect(0, 9, 20, 161));
        line_axisLeft_3->setFrameShape(QFrame::VLine);
        line_axisLeft_3->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(frame_2);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(140, 10, 20, 160));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_axisBottom_3 = new QFrame(frame_2);
        line_axisBottom_3->setObjectName(QStringLiteral("line_axisBottom_3"));
        line_axisBottom_3->setGeometry(QRect(10, 160, 141, 20));
        line_axisBottom_3->setFrameShape(QFrame::HLine);
        line_axisBottom_3->setFrameShadow(QFrame::Sunken);
        line_axisTop_3 = new QFrame(frame_2);
        line_axisTop_3->setObjectName(QStringLiteral("line_axisTop_3"));
        line_axisTop_3->setGeometry(QRect(10, 0, 141, 20));
        line_axisTop_3->setFrameShape(QFrame::HLine);
        line_axisTop_3->setFrameShadow(QFrame::Sunken);
        label_4 = new QLabel(frame_2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 20, 121, 21));
        label_4->setFont(font);
        label_4->setAlignment(Qt::AlignCenter);
        checkBox_isonetEnabled = new QCheckBox(frame_2);
        checkBox_isonetEnabled->setObjectName(QStringLiteral("checkBox_isonetEnabled"));
        checkBox_isonetEnabled->setEnabled(true);
        checkBox_isonetEnabled->setGeometry(QRect(20, 50, 121, 21));
        checkBox_isonetEnabled->setFont(font1);
        checkBox_isonetEnabled->setIconSize(QSize(16, 16));
        checkBox_isonetEnabled->setChecked(true);
        spinBox_isonetWidth = new QDoubleSpinBox(frame_2);
        spinBox_isonetWidth->setObjectName(QStringLiteral("spinBox_isonetWidth"));
        spinBox_isonetWidth->setGeometry(QRect(90, 80, 51, 22));
        spinBox_isonetWidth->setFont(font1);
        spinBox_isonetWidth->setDecimals(1);
        spinBox_isonetWidth->setMinimum(0.5);
        spinBox_isonetWidth->setMaximum(5);
        spinBox_isonetWidth->setSingleStep(0.1);
        spinBox_isonetWidth->setValue(1);
        label_5 = new QLabel(frame_2);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 80, 61, 21));
        label_5->setFont(font1);
        pushButton_isonetColor = new QPushButton(frame_2);
        pushButton_isonetColor->setObjectName(QStringLiteral("pushButton_isonetColor"));
        pushButton_isonetColor->setGeometry(QRect(20, 110, 91, 21));
        pushButton_isonetColor->setFont(font1);
        label_isonetColor = new QLabel(frame_2);
        label_isonetColor->setObjectName(QStringLiteral("label_isonetColor"));
        label_isonetColor->setGeometry(QRect(120, 110, 21, 21));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush5(QColor(239, 239, 239, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        label_isonetColor->setPalette(palette7);
        label_isonetColor->setAutoFillBackground(true);
        comboBox_isolinePeriodicy = new QComboBox(frame_2);
        comboBox_isolinePeriodicy->setObjectName(QStringLiteral("comboBox_isolinePeriodicy"));
        comboBox_isolinePeriodicy->setGeometry(QRect(20, 140, 121, 22));
        comboBox_isolinePeriodicy->setFont(font1);
        frame_axis_2 = new QFrame(SettingsWidgetCommon);
        frame_axis_2->setObjectName(QStringLiteral("frame_axis_2"));
        frame_axis_2->setGeometry(QRect(160, 60, 161, 151));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Base, brush);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush);
        frame_axis_2->setPalette(palette8);
        frame_axis_2->setAutoFillBackground(true);
        frame_axis_2->setFrameShape(QFrame::StyledPanel);
        frame_axis_2->setFrameShadow(QFrame::Raised);
        label_axis_2 = new QLabel(frame_axis_2);
        label_axis_2->setObjectName(QStringLiteral("label_axis_2"));
        label_axis_2->setGeometry(QRect(20, 20, 101, 21));
        label_axis_2->setFont(font);
        label_axis_2->setAlignment(Qt::AlignCenter);
        line_axisBottom_4 = new QFrame(frame_axis_2);
        line_axisBottom_4->setObjectName(QStringLiteral("line_axisBottom_4"));
        line_axisBottom_4->setGeometry(QRect(10, 130, 141, 20));
        line_axisBottom_4->setFrameShape(QFrame::HLine);
        line_axisBottom_4->setFrameShadow(QFrame::Sunken);
        line_axisTop_4 = new QFrame(frame_axis_2);
        line_axisTop_4->setObjectName(QStringLiteral("line_axisTop_4"));
        line_axisTop_4->setGeometry(QRect(10, 0, 141, 20));
        line_axisTop_4->setFrameShape(QFrame::HLine);
        line_axisTop_4->setFrameShadow(QFrame::Sunken);
        line_axisLeft_4 = new QFrame(frame_axis_2);
        line_axisLeft_4->setObjectName(QStringLiteral("line_axisLeft_4"));
        line_axisLeft_4->setGeometry(QRect(0, 9, 20, 131));
        line_axisLeft_4->setFrameShape(QFrame::VLine);
        line_axisLeft_4->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(frame_axis_2);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(140, 10, 20, 131));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        checkBox_timeEnabled = new QCheckBox(frame_axis_2);
        checkBox_timeEnabled->setObjectName(QStringLiteral("checkBox_timeEnabled"));
        checkBox_timeEnabled->setGeometry(QRect(20, 50, 121, 17));
        checkBox_timeEnabled->setFont(font1);
        label_9 = new QLabel(frame_axis_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 80, 51, 16));
        QFont font2;
        font2.setPointSize(12);
        label_9->setFont(font2);
        label_9->setAlignment(Qt::AlignCenter);
        lineEdit_timeVariableName = new QLineEdit(frame_axis_2);
        lineEdit_timeVariableName->setObjectName(QStringLiteral("lineEdit_timeVariableName"));
        lineEdit_timeVariableName->setEnabled(false);
        lineEdit_timeVariableName->setGeometry(QRect(70, 80, 71, 20));
        lineEdit_timeVariableName->setFont(font1);
        lineEdit_timeVariableName->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(frame_axis_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, 110, 61, 21));
        label_3->setFont(font1);
        spinBox_timeStep = new QDoubleSpinBox(frame_axis_2);
        spinBox_timeStep->setObjectName(QStringLiteral("spinBox_timeStep"));
        spinBox_timeStep->setEnabled(false);
        spinBox_timeStep->setGeometry(QRect(80, 110, 61, 22));
        spinBox_timeStep->setFont(font1);
        spinBox_timeStep->setDecimals(3);
        spinBox_timeStep->setMinimum(0.001);
        spinBox_timeStep->setMaximum(60);
        spinBox_timeStep->setSingleStep(0.001);
        spinBox_timeStep->setValue(0.05);
        frame_3 = new QFrame(SettingsWidgetCommon);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(330, 60, 161, 181));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Base, brush);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush);
        frame_3->setPalette(palette9);
        frame_3->setAutoFillBackground(true);
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        line_axisLeft_5 = new QFrame(frame_3);
        line_axisLeft_5->setObjectName(QStringLiteral("line_axisLeft_5"));
        line_axisLeft_5->setGeometry(QRect(0, 9, 20, 161));
        line_axisLeft_5->setFrameShape(QFrame::VLine);
        line_axisLeft_5->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(frame_3);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(140, 10, 20, 160));
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_axisBottom_5 = new QFrame(frame_3);
        line_axisBottom_5->setObjectName(QStringLiteral("line_axisBottom_5"));
        line_axisBottom_5->setGeometry(QRect(10, 160, 140, 20));
        line_axisBottom_5->setFrameShape(QFrame::HLine);
        line_axisBottom_5->setFrameShadow(QFrame::Sunken);
        line_axisTop_5 = new QFrame(frame_3);
        line_axisTop_5->setObjectName(QStringLiteral("line_axisTop_5"));
        line_axisTop_5->setGeometry(QRect(10, 0, 140, 20));
        line_axisTop_5->setFrameShape(QFrame::HLine);
        line_axisTop_5->setFrameShadow(QFrame::Sunken);
        label_10 = new QLabel(frame_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(20, 10, 121, 31));
        label_10->setFont(font);
        label_10->setAlignment(Qt::AlignCenter);
        label_12 = new QLabel(frame_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(20, 50, 121, 21));
        label_12->setFont(font1);
        label_15 = new QLabel(frame_3);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(20, 110, 61, 21));
        label_15->setFont(font1);
        spinBox_radius = new QDoubleSpinBox(frame_3);
        spinBox_radius->setObjectName(QStringLiteral("spinBox_radius"));
        spinBox_radius->setGeometry(QRect(90, 110, 51, 22));
        spinBox_radius->setFont(font1);
        spinBox_radius->setMinimum(0.1);
        spinBox_radius->setMaximum(10);
        spinBox_radius->setSingleStep(0.01);
        spinBox_radius->setValue(1);
        label_16 = new QLabel(frame_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(20, 140, 71, 21));
        label_16->setFont(font1);
        spinBox_scaleRate = new QDoubleSpinBox(frame_3);
        spinBox_scaleRate->setObjectName(QStringLiteral("spinBox_scaleRate"));
        spinBox_scaleRate->setGeometry(QRect(90, 140, 51, 22));
        spinBox_scaleRate->setFont(font1);
        spinBox_scaleRate->setMinimum(0.8);
        spinBox_scaleRate->setMaximum(1.25);
        spinBox_scaleRate->setSingleStep(0.01);
        spinBox_scaleRate->setValue(1);
        comboBox_surfaceQuality = new QComboBox(frame_3);
        comboBox_surfaceQuality->setObjectName(QStringLiteral("comboBox_surfaceQuality"));
        comboBox_surfaceQuality->setGeometry(QRect(20, 80, 121, 22));
        comboBox_surfaceQuality->setFont(font1);
        frame_4 = new QFrame(SettingsWidgetCommon);
        frame_4->setObjectName(QStringLiteral("frame_4"));
        frame_4->setGeometry(QRect(500, 60, 511, 181));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::Base, brush);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush);
        frame_4->setPalette(palette10);
        frame_4->setAutoFillBackground(true);
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        line_axisLeft_6 = new QFrame(frame_4);
        line_axisLeft_6->setObjectName(QStringLiteral("line_axisLeft_6"));
        line_axisLeft_6->setGeometry(QRect(0, 9, 20, 161));
        line_axisLeft_6->setFrameShape(QFrame::VLine);
        line_axisLeft_6->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(frame_4);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(490, 10, 20, 161));
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_axisBottom_6 = new QFrame(frame_4);
        line_axisBottom_6->setObjectName(QStringLiteral("line_axisBottom_6"));
        line_axisBottom_6->setGeometry(QRect(10, 160, 491, 20));
        line_axisBottom_6->setFrameShape(QFrame::HLine);
        line_axisBottom_6->setFrameShadow(QFrame::Sunken);
        line_axisTop_6 = new QFrame(frame_4);
        line_axisTop_6->setObjectName(QStringLiteral("line_axisTop_6"));
        line_axisTop_6->setGeometry(QRect(10, 0, 491, 20));
        line_axisTop_6->setFrameShape(QFrame::HLine);
        line_axisTop_6->setFrameShadow(QFrame::Sunken);
        label_13 = new QLabel(frame_4);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(20, 20, 151, 21));
        label_13->setFont(font);
        label_13->setAlignment(Qt::AlignCenter);
        lineEdit_configFile = new QLineEdit(frame_4);
        lineEdit_configFile->setObjectName(QStringLiteral("lineEdit_configFile"));
        lineEdit_configFile->setGeometry(QRect(20, 139, 61, 21));
        lineEdit_configFile->setFont(font1);
        lineEdit_configFile->setDragEnabled(false);
        lineEdit_configFile->setReadOnly(true);
        label_14 = new QLabel(frame_4);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(20, 110, 131, 21));
        label_14->setFont(font1);
        label_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButton_configFile = new QPushButton(frame_4);
        pushButton_configFile->setObjectName(QStringLiteral("pushButton_configFile"));
        pushButton_configFile->setGeometry(QRect(90, 140, 51, 21));
        pushButton_configFile->setFont(font1);
        comboBox_movingButton = new QComboBox(frame_4);
        comboBox_movingButton->setObjectName(QStringLiteral("comboBox_movingButton"));
        comboBox_movingButton->setGeometry(QRect(20, 80, 121, 22));
        comboBox_movingButton->setFont(font1);
        label_17 = new QLabel(frame_4);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(20, 50, 121, 21));
        label_17->setFont(font1);
        label_17->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(frame_4);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(190, 20, 151, 21));
        label_6->setFont(font1);
        checkBox_isLegendShowed = new QCheckBox(frame_4);
        checkBox_isLegendShowed->setObjectName(QStringLiteral("checkBox_isLegendShowed"));
        checkBox_isLegendShowed->setGeometry(QRect(160, 80, 91, 21));
        QFont font3;
        font3.setPointSize(9);
        checkBox_isLegendShowed->setFont(font3);
        slider_legendSize = new QSlider(frame_4);
        slider_legendSize->setObjectName(QStringLiteral("slider_legendSize"));
        slider_legendSize->setGeometry(QRect(180, 110, 141, 21));
        slider_legendSize->setMinimum(20);
        slider_legendSize->setMaximum(50);
        slider_legendSize->setValue(20);
        slider_legendSize->setOrientation(Qt::Horizontal);
        label_18 = new QLabel(frame_4);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(160, 110, 20, 21));
        label_18->setFont(font2);
        label_18->setAlignment(Qt::AlignCenter);
        label_19 = new QLabel(frame_4);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(320, 110, 21, 21));
        label_19->setFont(font2);
        label_19->setAlignment(Qt::AlignCenter);
        label_20 = new QLabel(frame_4);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(270, 80, 71, 21));
        label_20->setFont(font3);
        line_7 = new QFrame(frame_4);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(250, 80, 21, 21));
        line_7->setFrameShape(QFrame::VLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(frame_4);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(140, 50, 21, 111));
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        label_21 = new QLabel(frame_4);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(320, 50, 21, 21));
        label_21->setFont(font2);
        label_21->setAlignment(Qt::AlignCenter);
        label_22 = new QLabel(frame_4);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(160, 50, 20, 21));
        label_22->setFont(font2);
        label_22->setAlignment(Qt::AlignCenter);
        slider_verticalscale = new QSlider(frame_4);
        slider_verticalscale->setObjectName(QStringLiteral("slider_verticalscale"));
        slider_verticalscale->setGeometry(QRect(180, 50, 141, 21));
        slider_verticalscale->setMinimum(1);
        slider_verticalscale->setMaximum(25);
        slider_verticalscale->setOrientation(Qt::Horizontal);
        slider_legendOpacity = new QSlider(frame_4);
        slider_legendOpacity->setObjectName(QStringLiteral("slider_legendOpacity"));
        slider_legendOpacity->setGeometry(QRect(180, 140, 141, 21));
        slider_legendOpacity->setMinimum(0);
        slider_legendOpacity->setMaximum(100);
        slider_legendOpacity->setValue(50);
        slider_legendOpacity->setOrientation(Qt::Horizontal);
        label_23 = new QLabel(frame_4);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(320, 140, 21, 21));
        label_23->setFont(font2);
        label_23->setAlignment(Qt::AlignCenter);
        label_24 = new QLabel(frame_4);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(160, 140, 20, 21));
        label_24->setFont(font2);
        label_24->setAlignment(Qt::AlignCenter);
        line_10 = new QFrame(frame_4);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(340, 20, 21, 141));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        checkBox_perspective = new QCheckBox(frame_4);
        checkBox_perspective->setObjectName(QStringLiteral("checkBox_perspective"));
        checkBox_perspective->setGeometry(QRect(360, 20, 131, 21));
        checkBox_perspective->setFont(font1);
        checkBox_proportions = new QCheckBox(frame_4);
        checkBox_proportions->setObjectName(QStringLiteral("checkBox_proportions"));
        checkBox_proportions->setGeometry(QRect(360, 50, 131, 21));
        checkBox_proportions->setFont(font1);
        lineEdit_functionString = new QLineEdit(SettingsWidgetCommon);
        lineEdit_functionString->setObjectName(QStringLiteral("lineEdit_functionString"));
        lineEdit_functionString->setGeometry(QRect(160, 10, 1171, 41));
        QFont font4;
        font4.setFamily(QStringLiteral("Gabriola"));
        font4.setPointSize(22);
        lineEdit_functionString->setFont(font4);
        lineEdit_functionString->setAlignment(Qt::AlignCenter);
        label_function = new QLabel(SettingsWidgetCommon);
        label_function->setObjectName(QStringLiteral("label_function"));
        label_function->setGeometry(QRect(10, 10, 141, 71));
        QFont font5;
        font5.setPointSize(35);
        label_function->setFont(font5);
        label_function->setAlignment(Qt::AlignCenter);

        retranslateUi(SettingsWidgetCommon);

        QMetaObject::connectSlotsByName(SettingsWidgetCommon);
    } // setupUi

    void retranslateUi(QWidget *SettingsWidgetCommon)
    {
        SettingsWidgetCommon->setWindowTitle(QApplication::translate("SettingsWidgetCommon", "Form", 0));
        label_axis->setText(QApplication::translate("SettingsWidgetCommon", "Axis:", 0));
        comboBox_axis->clear();
        comboBox_axis->insertItems(0, QStringList()
         << QApplication::translate("SettingsWidgetCommon", "No axis", 0)
         << QApplication::translate("SettingsWidgetCommon", "Central axis", 0)
         << QApplication::translate("SettingsWidgetCommon", "Bounding axis", 0)
         << QApplication::translate("SettingsWidgetCommon", "Cellular axis", 0)
        );
        label_colorX->setText(QString());
        pushButton_colorX->setText(QApplication::translate("SettingsWidgetCommon", "Var1", 0));
        label_colorY->setText(QString());
        pushButton_colorY->setText(QApplication::translate("SettingsWidgetCommon", "Var2", 0));
        label_colorZ->setText(QString());
        pushButton_colorZ->setText(QApplication::translate("SettingsWidgetCommon", "Func", 0));
        label->setText(QApplication::translate("SettingsWidgetCommon", "Net:", 0));
        checkBox_netEnabled->setText(QApplication::translate("SettingsWidgetCommon", "Enabled", 0));
        spinBox_netWidth->setPrefix(QString());
        label_2->setText(QApplication::translate("SettingsWidgetCommon", "Width", 0));
        pushButton_netColor->setText(QApplication::translate("SettingsWidgetCommon", "Color", 0));
        label_netColor->setText(QString());
        label_4->setText(QApplication::translate("SettingsWidgetCommon", "Isonet:", 0));
        checkBox_isonetEnabled->setText(QApplication::translate("SettingsWidgetCommon", "Enable", 0));
        spinBox_isonetWidth->setPrefix(QString());
        label_5->setText(QApplication::translate("SettingsWidgetCommon", "Width", 0));
        pushButton_isonetColor->setText(QApplication::translate("SettingsWidgetCommon", "Color", 0));
        label_isonetColor->setText(QString());
        comboBox_isolinePeriodicy->clear();
        comboBox_isolinePeriodicy->insertItems(0, QStringList()
         << QApplication::translate("SettingsWidgetCommon", "Very low", 0)
         << QApplication::translate("SettingsWidgetCommon", "Low", 0)
         << QApplication::translate("SettingsWidgetCommon", "Decreased", 0)
         << QApplication::translate("SettingsWidgetCommon", "Middle", 0)
         << QApplication::translate("SettingsWidgetCommon", "Increased", 0)
         << QApplication::translate("SettingsWidgetCommon", "High", 0)
         << QApplication::translate("SettingsWidgetCommon", "Very high", 0)
         << QApplication::translate("SettingsWidgetCommon", "Ultra high", 0)
        );
        label_axis_2->setText(QApplication::translate("SettingsWidgetCommon", "Time:", 0));
        checkBox_timeEnabled->setText(QApplication::translate("SettingsWidgetCommon", "Enabled", 0));
        label_9->setText(QApplication::translate("SettingsWidgetCommon", "Name:", 0));
        lineEdit_timeVariableName->setText(QApplication::translate("SettingsWidgetCommon", "t", 0));
        label_3->setText(QApplication::translate("SettingsWidgetCommon", "Step, ms:", 0));
        label_10->setText(QApplication::translate("SettingsWidgetCommon", "Scene:", 0));
        label_12->setText(QApplication::translate("SettingsWidgetCommon", "Quality:", 0));
        label_15->setText(QApplication::translate("SettingsWidgetCommon", "Distance", 0));
        label_16->setText(QApplication::translate("SettingsWidgetCommon", "Scale rate", 0));
        comboBox_surfaceQuality->clear();
        comboBox_surfaceQuality->insertItems(0, QStringList()
         << QApplication::translate("SettingsWidgetCommon", "Very low", 0)
         << QApplication::translate("SettingsWidgetCommon", "Low", 0)
         << QApplication::translate("SettingsWidgetCommon", "Decreased", 0)
         << QApplication::translate("SettingsWidgetCommon", "Middle", 0)
         << QApplication::translate("SettingsWidgetCommon", "Increased", 0)
         << QApplication::translate("SettingsWidgetCommon", "High", 0)
         << QApplication::translate("SettingsWidgetCommon", "Very high", 0)
         << QApplication::translate("SettingsWidgetCommon", "Ultra high", 0)
        );
        label_13->setText(QApplication::translate("SettingsWidgetCommon", "Other:", 0));
        label_14->setText(QApplication::translate("SettingsWidgetCommon", "Config file:", 0));
        pushButton_configFile->setText(QApplication::translate("SettingsWidgetCommon", "Browse", 0));
        comboBox_movingButton->clear();
        comboBox_movingButton->insertItems(0, QStringList()
         << QApplication::translate("SettingsWidgetCommon", "Left button", 0)
         << QApplication::translate("SettingsWidgetCommon", "Wheel button", 0)
         << QApplication::translate("SettingsWidgetCommon", "Right button", 0)
        );
        label_17->setText(QApplication::translate("SettingsWidgetCommon", "Rotating m. button:", 0));
        label_6->setText(QApplication::translate("SettingsWidgetCommon", "Vertical scale:", 0));
        checkBox_isLegendShowed->setText(QApplication::translate("SettingsWidgetCommon", "Show legend", 0));
        label_18->setText(QApplication::translate("SettingsWidgetCommon", "-", 0));
        label_19->setText(QApplication::translate("SettingsWidgetCommon", "+", 0));
        label_20->setText(QApplication::translate("SettingsWidgetCommon", "Size, opacity:", 0));
        label_21->setText(QApplication::translate("SettingsWidgetCommon", "+", 0));
        label_22->setText(QApplication::translate("SettingsWidgetCommon", "-", 0));
        label_23->setText(QApplication::translate("SettingsWidgetCommon", "+", 0));
        label_24->setText(QApplication::translate("SettingsWidgetCommon", "-", 0));
        checkBox_perspective->setText(QApplication::translate("SettingsWidgetCommon", "Perspective", 0));
        checkBox_proportions->setText(QApplication::translate("SettingsWidgetCommon", "Native proportions", 0));
        lineEdit_functionString->setText(QString());
        label_function->setText(QApplication::translate("SettingsWidgetCommon", "F =", 0));
    } // retranslateUi

};

namespace Ui {
    class SettingsWidgetCommon: public Ui_SettingsWidgetCommon {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SETTINGSWIDGETCOMMON_H
